In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
data=pd.read_csv('insurance.csv')
(data.columns)
data.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [42]:
x=data.iloc[:,[0,2,5,3]].values
y=data.iloc[:,6].values
x
y

array([16884.924 ,  1725.5523,  4449.462 , ...,  1629.8335,  2007.945 ,
       29141.3603])

In [43]:
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])
print(x[:,2])

[3 2 2 ... 2 3 1]


In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)
print(x_train)
print(x_test)
print(y_train)
print(y_test)

[[53 26.6 1 0]
 [53 21.4 3 1]
 [18 37.29 2 0]
 ...
 [51 34.96 0 2]
 [40 22.22 2 2]
 [57 27.94 2 1]]
[[19 35.53 1 0]
 [57 31.54 1 0]
 [51 37.0 3 0]
 ...
 [47 38.94 2 2]
 [19 36.575 1 0]
 [35 26.125 0 0]]
[10355.641  10065.413   1141.4451 ... 44641.1974 19444.2658 11554.2236]
[ 1646.4297  11353.2276   8798.593   10381.4787   2103.08    38746.3551
  9304.7019  11658.11505  3070.8087  19539.243   12629.8967  11538.421
  6338.0756   7050.642    1137.4697   8968.33    21984.47061  6414.178
 28287.89766 13462.52     9722.7695  40932.4295   8026.6666   8444.474
  2203.47185  6664.68595  8606.2174   8283.6807   5375.038    3645.0894
 11674.13    11737.84884 24873.3849  33750.2918  24180.9335   9863.4718
 36837.467   17942.106   11856.4115  39725.51805  4349.462   11743.9341
 19749.38338 12347.172    4931.647   30259.99556 27724.28875 34672.1472
  9644.2525  14394.39815 12557.6053  11881.358    2352.96845  9101.798
 17178.6824   3994.1778  40941.2854  12644.589   22395.74424  1149.3959
  3366.66

In [45]:
regressor=RandomForestRegressor(criterion="mse")
regressor.fit(x,y) 

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=None, oob_score=False,
                      random_state=None, verbose=0, warm_start=False)

In [ ]:
 clf = RandomForestRegressor(random_state=0)

In [ ]:
y_pred=regressor.predict(x_test)
y_pred

array([ 3111.414626  , 14243.2240936 , 10168.2741242 , 12778.3446929 ,
        2566.3623395 , 31519.3958295 , 10735.0005889 , 12021.7075231 ,
        3619.0495785 , 15715.286124  , 13493.9581929 , 14385.2504686 ,
        6818.7077029 ,  8897.3676259 ,  2490.430375  ,  9668.7944501 ,
       17168.3032037 ,  7688.7986189 , 31855.6512981 , 16063.1670629 ,
       10877.5272625 , 29458.8592597 , 11036.6318022 , 10157.9754174 ,
       10389.35722309,  7433.8050688 , 14902.5503458 , 17131.7120031 ,
        9908.4251836 ,  5225.624039  , 11567.3495321 , 11684.6557146 ,
       20827.112397  , 23681.8203328 , 21437.5985825 , 11223.672336  ,
       33818.7057076 , 13366.708069  , 13969.4969466 , 30521.5503422 ,
        5709.616635  , 12590.2136202 , 18409.5790956 , 22522.4529996 ,
        7615.7344218 , 24579.4179851 , 19645.520016  , 26153.442058  ,
        9752.924094  , 15685.4425825 , 16494.2393329 , 13040.1345889 ,
        5968.0291049 ,  9369.410742  , 14884.0560696 ,  7704.1841571 ,
      

In [ ]:
a=(input("enter bmi"))
b=(input("enter children"))
c=int(input("enter region"))
d=(input("enter age"))

enter bmi27.9
enter children3
enter region2
enter age45


In [46]:
t1=([[a,b,c,d]])
pt1=regressor.predict(t1)
pt1

array([15649.1206211])